version: '3.8'
services:
  dev-db:
    image: docker.arvancloud.ir/postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nest-tutorial
    networks:
      - nest_tutorial_network

networks:
  nest_tutorial_network:
